/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed8;
  GtkWidget *entry27;
  GtkWidget *entry29;
  GtkWidget *entry30;
  GtkWidget *entry31;
  GtkWidget *entry52;
  GtkWidget *label57;
  GtkWidget *label56;
  GtkWidget *label55;
  GtkWidget *comboboxentry4;
  GtkWidget *button8;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label95;
  GtkWidget *label53;
  GtkWidget *label82;
  GtkWidget *label54;
  GtkWidget *comboboxentryjour1;
  GtkWidget *label61;
  GtkWidget *label60;
  GtkWidget *comboboxentrymois1;
  GtkWidget *comboboxentryanne1;
  GtkWidget *labelAjouter;
  GtkWidget *fixed9;
  GtkWidget *entry33;
  GtkWidget *entry34;
  GtkWidget *entry36;
  GtkWidget *entry37;
  GtkWidget *entry39;
  GtkWidget *entry40;
  GtkWidget *entry41;
  GtkWidget *label65;
  GtkWidget *label70;
  GtkWidget *label64;
  GtkWidget *label63;
  GtkWidget *label62;
  GtkWidget *label67;
  GtkWidget *comboboxentry5;
  GtkWidget *label66;
  GtkWidget *comboboxentry1;
  GtkWidget *comboboxentry2;
  GtkWidget *comboboxentry3;
  GtkWidget *label71;
  GtkWidget *button10;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label96;
  GtkWidget *button9;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label69;
  GtkWidget *button11;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label83;
  GtkWidget *label68;
  GtkWidget *label49;
  GtkWidget *fixed10;
  GtkWidget *entry42;
  GtkWidget *button12;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label97;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *buttonRsupp;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label85;
  GtkWidget *label50;
  GtkWidget *fixed11;
  GtkWidget *vseparator2;
  GtkWidget *treeview2;
  GtkWidget *label75;
  GtkWidget *button13;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label86;
  GtkWidget *buttonaAfficher;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label87;
  GtkWidget *label51;
  GtkWidget *fixed12;
  GtkWidget *treeview3;
  GtkWidget *label78;
  GtkWidget *button14;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label89;
  GtkWidget *buttonAfficheval;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label88;
  GtkWidget *label52;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed8), entry27, 192, 128);
  gtk_widget_set_size_request (entry27, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed8), entry29, 600, 160);
  gtk_widget_set_size_request (entry29, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed8), entry30, 600, 264);
  gtk_widget_set_size_request (entry30, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed8), entry31, 192, 312);
  gtk_widget_set_size_request (entry31, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  entry52 = gtk_entry_new ();
  gtk_widget_show (entry52);
  gtk_fixed_put (GTK_FIXED (fixed8), entry52, 192, 408);
  gtk_widget_set_size_request (entry52, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry52), 8226);

  label57 = gtk_label_new (_("Ajouter un capteur"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed8), label57, 384, 32);
  gtk_widget_set_size_request (label57, 216, 56);

  label56 = gtk_label_new (_("Nom"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed8), label56, 104, 128);
  gtk_widget_set_size_request (label56, 64, 32);

  label55 = gtk_label_new (_("Type"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed8), label55, 80, 224);
  gtk_widget_set_size_request (label55, 104, 24);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry4, 192, 216);
  gtk_widget_set_size_request (comboboxentry4, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("hydraulique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("humidite"));

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed8), button8, 384, 520);
  gtk_widget_set_size_request (button8, 160, 56);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button8), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox21), label95, FALSE, FALSE, 0);

  label53 = gtk_label_new (_("Etat"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed8), label53, 88, 320);
  gtk_widget_set_size_request (label53, 88, 24);

  label82 = gtk_label_new (_("Position"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed8), label82, 96, 416);
  gtk_widget_set_size_request (label82, 81, 24);

  label54 = gtk_label_new (_("ID"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed8), label54, 496, 168);
  gtk_widget_set_size_request (label54, 72, 24);

  comboboxentryjour1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryjour1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentryjour1, 600, 376);
  gtk_widget_set_size_request (comboboxentryjour1, 77, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour1), _("31"));

  label61 = gtk_label_new (_("Date"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed8), label61, 512, 384);
  gtk_widget_set_size_request (label61, 49, 17);

  label60 = gtk_label_new (_("Valeur"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed8), label60, 512, 272);
  gtk_widget_set_size_request (label60, 49, 17);

  comboboxentrymois1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymois1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentrymois1, 680, 376);
  gtk_widget_set_size_request (comboboxentrymois1, 69, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois1), _("12"));

  comboboxentryanne1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryanne1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentryanne1, 752, 376);
  gtk_widget_set_size_request (comboboxentryanne1, 96, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1910"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1911"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1912"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1913"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1914"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1915"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1916"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1917"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1918"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1919"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1920"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1921"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1922"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1923"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1924"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1925"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1926"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1927"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1928"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1929"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1930"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1931"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1932"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1933"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1934"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1935"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1936"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1937"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1938"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1939"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1940"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1941"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1942"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1943"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1944"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1945"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1946"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1947"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1948"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1949"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1950"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1951"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1952"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1953"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1954"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1955"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1956"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1957"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1958"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1959"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1960"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1961"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1962"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1963"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1964"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1965"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1966"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1967"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1968"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1969"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1970"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1971"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1972"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1973"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1974"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1975"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1976"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1977"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1978"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1979"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1980"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1981"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1982"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1983"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1984"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1985"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1986"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1987"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1988"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1989"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("1999 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("2000 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryanne1), _("2004"));

  labelAjouter = gtk_label_new (_("Ajouter"));
  gtk_widget_show (labelAjouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelAjouter);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  entry33 = gtk_entry_new ();
  gtk_widget_show (entry33);
  gtk_fixed_put (GTK_FIXED (fixed9), entry33, 240, 120);
  gtk_widget_set_size_request (entry33, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry33), 8226);

  entry34 = gtk_entry_new ();
  gtk_widget_show (entry34);
  gtk_fixed_put (GTK_FIXED (fixed9), entry34, 240, 176);
  gtk_widget_set_size_request (entry34, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed9), entry36, 240, 288);
  gtk_widget_set_size_request (entry36, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed9), entry37, 240, 344);
  gtk_widget_set_size_request (entry37, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  entry39 = gtk_entry_new ();
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed9), entry39, 240, 64);
  gtk_widget_set_size_request (entry39, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  entry40 = gtk_entry_new ();
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed9), entry40, 240, 344);
  gtk_widget_set_size_request (entry40, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  entry41 = gtk_entry_new ();
  gtk_widget_show (entry41);
  gtk_fixed_put (GTK_FIXED (fixed9), entry41, 240, 464);
  gtk_widget_set_size_request (entry41, 304, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry41), 8226);

  label65 = gtk_label_new (_("Nom"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed9), label65, 96, 128);
  gtk_widget_set_size_request (label65, 49, 17);

  label70 = gtk_label_new (_("ID capteur \303\240 modifier"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed9), label70, 56, 72);
  gtk_widget_set_size_request (label70, 152, 24);

  label64 = gtk_label_new (_("ID"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed9), label64, 96, 184);
  gtk_widget_set_size_request (label64, 49, 17);

  label63 = gtk_label_new (_("Type"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed9), label63, 88, 240);
  gtk_widget_set_size_request (label63, 72, 24);

  label62 = gtk_label_new (_("Valeur"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed9), label62, 104, 360);
  gtk_widget_set_size_request (label62, 49, 17);

  label67 = gtk_label_new (_("Etat"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed9), label67, 104, 304);
  gtk_widget_set_size_request (label67, 49, 17);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry5, 240, 232);
  gtk_widget_set_size_request (comboboxentry5, 304, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("hydraulique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("humidite"));

  label66 = gtk_label_new (_("Date"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed9), label66, 104, 416);
  gtk_widget_set_size_request (label66, 49, 17);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry1, 240, 400);
  gtk_widget_set_size_request (comboboxentry1, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("31"));

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry2, 336, 400);
  gtk_widget_set_size_request (comboboxentry2, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("12"));

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry3, 432, 400);
  gtk_widget_set_size_request (comboboxentry3, 112, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1910"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1911"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1912"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1913"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1914"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1915"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1916"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1917"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1918"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1919"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1920"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1921"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1922"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1923"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1924"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1925"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1926"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1927"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1928"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1929"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1930"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1931"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1932"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1933"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1934"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1935"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1936"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1937"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1938"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1939"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1940"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1941"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1942"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1943"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1944"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1945"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1946"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1947"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1948"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1949"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1950"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1951"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1952"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1953"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1954"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1955"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1956"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1957"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1958"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1959"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1960"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1961"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1962"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1963"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1964"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1965"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1966"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1967"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1968"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1969"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1970"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1971"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1972"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1973"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1974"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1975"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1976"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1977"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1978"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1979"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1980"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1981"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1982"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1983"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1984"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1985"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1986"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1987"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1988"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1989"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("1999 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("2000 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("2004"));

  label71 = gtk_label_new (_("Position"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed9), label71, 88, 472);
  gtk_widget_set_size_request (label71, 80, 24);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed9), button10, 616, 64);
  gtk_widget_set_size_request (button10, 128, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button10), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox22), label96, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed9), button9, 424, 576);
  gtk_widget_set_size_request (button9, 152, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button9), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox10), label69, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed9), button11, 624, 576);
  gtk_widget_set_size_request (button11, 160, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button11), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox12), label83, FALSE, FALSE, 0);

  label68 = gtk_label_new (_("Modifier un capteur"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed9), label68, 472, 0);
  gtk_widget_set_size_request (label68, 248, 64);

  label49 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label49);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  entry42 = gtk_entry_new ();
  gtk_widget_show (entry42);
  gtk_fixed_put (GTK_FIXED (fixed10), entry42, 312, 128);
  gtk_widget_set_size_request (entry42, 248, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry42), 8226);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed10), button12, 592, 128);
  gtk_widget_set_size_request (button12, 176, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button12), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox23), label97, FALSE, FALSE, 0);

  label72 = gtk_label_new (_("Supprimer un capteur"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed10), label72, 472, 24);
  gtk_widget_set_size_request (label72, 184, 24);

  label73 = gtk_label_new (_("ID :"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed10), label73, 176, 128);
  gtk_widget_set_size_request (label73, 104, 32);

  buttonRsupp = gtk_button_new ();
  gtk_widget_show (buttonRsupp);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonRsupp, 488, 312);
  gtk_widget_set_size_request (buttonRsupp, 200, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonRsupp), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox14), label85, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label50);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator2, 480, 264);
  gtk_widget_set_size_request (vseparator2, 16, 16);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview2, 224, 104);
  gtk_widget_set_size_request (treeview2, 784, 352);

  label75 = gtk_label_new (_("Liste des capteurs"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed11), label75, 416, 8);
  gtk_widget_set_size_request (label75, 352, 80);
  gtk_label_set_justify (GTK_LABEL (label75), GTK_JUSTIFY_CENTER);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed11), button13, 952, 544);
  gtk_widget_set_size_request (button13, 144, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button13), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox15), label86, FALSE, FALSE, 0);

  buttonaAfficher = gtk_button_new ();
  gtk_widget_show (buttonaAfficher);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonaAfficher, 40, 240);
  gtk_widget_set_size_request (buttonaAfficher, 152, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonaAfficher), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("Afficher tous"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox16), label87, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label51);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview3, 200, 128);
  gtk_widget_set_size_request (treeview3, 776, 336);

  label78 = gtk_label_new (_("Les num\303\251ros de capteurs ayant des valeurs alarmantes:"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed12), label78, 432, 32);
  gtk_widget_set_size_request (label78, 416, 48);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed12), button14, 928, 536);
  gtk_widget_set_size_request (button14, 160, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button14), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox18), label89, FALSE, FALSE, 0);

  buttonAfficheval = gtk_button_new ();
  gtk_widget_show (buttonAfficheval);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonAfficheval, 48, 248);
  gtk_widget_set_size_request (buttonAfficheval, 120, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonAfficheval), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Afficher tous"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox17), label88, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("valeur alarmente"));
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label52);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_valider_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_rechercher_a_modofierbutton10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_valider_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_valider_sup_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRsupp, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaAfficher, "clicked",
                    G_CALLBACK (on_buttonaAfficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficheval, "clicked",
                    G_CALLBACK (on_buttonAfficheval_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window1, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window1, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (window1, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (window1, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (window1, entry52, "entry52");
  GLADE_HOOKUP_OBJECT (window1, label57, "label57");
  GLADE_HOOKUP_OBJECT (window1, label56, "label56");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, label95, "label95");
  GLADE_HOOKUP_OBJECT (window1, label53, "label53");
  GLADE_HOOKUP_OBJECT (window1, label82, "label82");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");
  GLADE_HOOKUP_OBJECT (window1, comboboxentryjour1, "comboboxentryjour1");
  GLADE_HOOKUP_OBJECT (window1, label61, "label61");
  GLADE_HOOKUP_OBJECT (window1, label60, "label60");
  GLADE_HOOKUP_OBJECT (window1, comboboxentrymois1, "comboboxentrymois1");
  GLADE_HOOKUP_OBJECT (window1, comboboxentryanne1, "comboboxentryanne1");
  GLADE_HOOKUP_OBJECT (window1, labelAjouter, "labelAjouter");
  GLADE_HOOKUP_OBJECT (window1, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window1, entry33, "entry33");
  GLADE_HOOKUP_OBJECT (window1, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (window1, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (window1, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (window1, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (window1, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (window1, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (window1, label65, "label65");
  GLADE_HOOKUP_OBJECT (window1, label70, "label70");
  GLADE_HOOKUP_OBJECT (window1, label64, "label64");
  GLADE_HOOKUP_OBJECT (window1, label63, "label63");
  GLADE_HOOKUP_OBJECT (window1, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (window1, label66, "label66");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (window1, label71, "label71");
  GLADE_HOOKUP_OBJECT (window1, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window1, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, label96, "label96");
  GLADE_HOOKUP_OBJECT (window1, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label69, "label69");
  GLADE_HOOKUP_OBJECT (window1, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label83, "label83");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window1, entry42, "entry42");
  GLADE_HOOKUP_OBJECT (window1, button12, "button12");
  GLADE_HOOKUP_OBJECT (window1, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window1, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, label97, "label97");
  GLADE_HOOKUP_OBJECT (window1, label72, "label72");
  GLADE_HOOKUP_OBJECT (window1, label73, "label73");
  GLADE_HOOKUP_OBJECT (window1, buttonRsupp, "buttonRsupp");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label85, "label85");
  GLADE_HOOKUP_OBJECT (window1, label50, "label50");
  GLADE_HOOKUP_OBJECT (window1, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window1, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, label75, "label75");
  GLADE_HOOKUP_OBJECT (window1, button13, "button13");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label86, "label86");
  GLADE_HOOKUP_OBJECT (window1, buttonaAfficher, "buttonaAfficher");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, label87, "label87");
  GLADE_HOOKUP_OBJECT (window1, label51, "label51");
  GLADE_HOOKUP_OBJECT (window1, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window1, label78, "label78");
  GLADE_HOOKUP_OBJECT (window1, button14, "button14");
  GLADE_HOOKUP_OBJECT (window1, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label89, "label89");
  GLADE_HOOKUP_OBJECT (window1, buttonAfficheval, "buttonAfficheval");
  GLADE_HOOKUP_OBJECT (window1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label88, "label88");
  GLADE_HOOKUP_OBJECT (window1, label52, "label52");

  return window1;
}

GtkWidget*
create_Inscription (void)
{
  GtkWidget *Inscription;
  GtkWidget *fixed13;
  GtkWidget *entry1_nom;
  GtkWidget *entry2_Mot;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *button1_insc;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label92;
  GtkWidget *button2_auth;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label93;
  GtkWidget *label94;

  Inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Inscription), _("Inscription"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (Inscription), fixed13);

  entry1_nom = gtk_entry_new ();
  gtk_widget_show (entry1_nom);
  gtk_fixed_put (GTK_FIXED (fixed13), entry1_nom, 224, 128);
  gtk_widget_set_size_request (entry1_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_nom), 8226);

  entry2_Mot = gtk_entry_new ();
  gtk_widget_show (entry2_Mot);
  gtk_fixed_put (GTK_FIXED (fixed13), entry2_Mot, 224, 192);
  gtk_widget_set_size_request (entry2_Mot, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_Mot), 8226);

  label90 = gtk_label_new (_("Nom"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed13), label90, 120, 136);
  gtk_widget_set_size_request (label90, 49, 17);

  label91 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed13), label91, 96, 192);
  gtk_widget_set_size_request (label91, 104, 24);

  button1_insc = gtk_button_new ();
  gtk_widget_show (button1_insc);
  gtk_fixed_put (GTK_FIXED (fixed13), button1_insc, 120, 264);
  gtk_widget_set_size_request (button1_insc, 136, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button1_insc), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Inscription"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox19), label92, FALSE, FALSE, 0);

  button2_auth = gtk_button_new ();
  gtk_widget_show (button2_auth);
  gtk_fixed_put (GTK_FIXED (fixed13), button2_auth, 328, 264);
  gtk_widget_set_size_request (button2_auth, 160, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button2_auth), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Connexion"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox20), label93, FALSE, FALSE, 0);

  label94 = gtk_label_new (_("Bienvenue \303\240 l'espace de gestionnaire de capteur"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed13), label94, 40, 32);
  gtk_widget_set_size_request (label94, 448, 80);

  g_signal_connect ((gpointer) button1_insc, "clicked",
                    G_CALLBACK (on_button1_insc_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_auth, "clicked",
                    G_CALLBACK (on_button2_auth_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Inscription, Inscription, "Inscription");
  GLADE_HOOKUP_OBJECT (Inscription, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Inscription, entry1_nom, "entry1_nom");
  GLADE_HOOKUP_OBJECT (Inscription, entry2_Mot, "entry2_Mot");
  GLADE_HOOKUP_OBJECT (Inscription, label90, "label90");
  GLADE_HOOKUP_OBJECT (Inscription, label91, "label91");
  GLADE_HOOKUP_OBJECT (Inscription, button1_insc, "button1_insc");
  GLADE_HOOKUP_OBJECT (Inscription, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Inscription, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Inscription, image19, "image19");
  GLADE_HOOKUP_OBJECT (Inscription, label92, "label92");
  GLADE_HOOKUP_OBJECT (Inscription, button2_auth, "button2_auth");
  GLADE_HOOKUP_OBJECT (Inscription, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Inscription, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Inscription, image20, "image20");
  GLADE_HOOKUP_OBJECT (Inscription, label93, "label93");
  GLADE_HOOKUP_OBJECT (Inscription, label94, "label94");

  return Inscription;
}

